minetest.register_node("tstdrm_liquid:water_source", {
	description = ("Water Source"),
	drawtype = "liquid",
	waving = 3,
	tiles = {
		{
			name = "tstdrm_water_animated.png",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
		},
		{
			name = "tstdrm_water_animated.png",
			backface_culling = true,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
		},
	},
	use_texture_alpha = "blend",
	paramtype = "light",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drop = "",
	drowning = 1,
	liquidtype = "source",
	liquid_alternative_flowing = "tstdrm_liquid:water_flowing",
	liquid_alternative_source = "tstdrm_liquid:water_source",
	liquid_viscosity = 1,
	post_effect_color = {a = 128, r = 200, g = 200, b = 230},
	groups = {water = 3, liquid = 3, cools_lava = 1},
--	sounds = default.node_sound_water_defaults(),
})

minetest.register_node("tstdrm_liquid:water_flowing", {
	description = ("Flowing Water"),
	drawtype = "flowingliquid",
	waving = 3,
	tiles = {"tstdrm_water.png"},
	special_tiles = {
		{
			name = "tstdrm_water_animated.png",
			backface_culling = false,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 0.5,
			},
		},
		{
			name = "tstdrm_water_animated.png",
			backface_culling = true,
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 0.5,
			},
		},
	},
	use_texture_alpha = "blend",
	paramtype = "light",
	paramtype2 = "flowingliquid",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drop = "",
	drowning = 1,
	liquidtype = "flowing",
	liquid_alternative_flowing = "tstdrm_liquid:water_flowing",
	liquid_alternative_source = "tstdrm_liquid:water_source",
	liquid_viscosity = 1,
	post_effect_color = {a = 128, r = 200, g = 200, b = 230},
	groups = {water = 3, liquid = 3, not_in_creative_inventory = 1,
		cools_lava = 1},
--	sounds = default.node_sound_water_defaults(),
})